# Generated by Django 5.2.17 on 2026-10-04 17:54

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='지점명')),
                ('edit_version', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False, help_text='최초 공개는 본점으로 지정됩니다. 공개 후 저장은 즉시 반영됩니다.', verbose_name='공개')),
                ('is_main', models.BooleanField(default=False, help_text='공개 지점을 본점으로 지정하면 기존 본점 지정이 함께 해제됩니다.', verbose_name='본점')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('summary', models.TextField(blank=True, max_length=1000, verbose_name='짧은 소개')),
                ('cover_alt', models.CharField(blank=True, max_length=200, verbose_name='대표 사진 대체 설명')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='기본 주소')),
                ('address_detail', models.CharField(blank=True, max_length=255, verbose_name='상세 주소')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='전화번호')),
                ('kakao_channel_url', models.URLField(blank=True, max_length=300, verbose_name='카카오톡 채널')),
                ('business_hours', models.TextField(blank=True, max_length=1000, verbose_name='운영시간')),
                ('closed_days', models.CharField(blank=True, max_length=255, verbose_name='휴무 안내')),
                ('parking_info', models.TextField(blank=True, max_length=2000, verbose_name='주차 안내')),
                ('usage_notes', models.TextField(blank=True, max_length=5000, verbose_name='기타 이용안내')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_covers', to='wagtailimages.image', verbose_name='대표 사진')),
            ],
            options={
                'verbose_name': '지점',
                'verbose_name_plural': '지점',
                'ordering': ['-is_main', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BranchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='사진 설명')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='대체 설명')),
                ('branch', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.branch')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_photos', to='wagtailimages.image', verbose_name='시설 사진')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('edit_version', models.PositiveIntegerField(default=0)),
                ('brand_name', models.CharField(max_length=100, verbose_name='브랜드명')),
                ('logo_alt', models.CharField(blank=True, max_length=200, verbose_name='로고 대체 설명')),
                ('hero_title', models.CharField(blank=True, max_length=160, verbose_name='대표 소개 제목')),
                ('hero_description', models.TextField(blank=True, max_length=2000, verbose_name='대표 소개 문구')),
                ('hero_alt', models.CharField(blank=True, max_length=200, verbose_name='대표 사진 대체 설명')),
                ('introduction', models.TextField(blank=True, max_length=5000, verbose_name='소개 문구')),
                ('introduction_alt', models.CharField(blank=True, max_length=200, verbose_name='소개 사진 대체 설명')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_heroes', to='wagtailimages.image', verbose_name='대표 사진')),
                ('introduction_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_introductions', to='wagtailimages.image', verbose_name='소개 사진')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_logos', to='wagtailimages.image', verbose_name='로고')),
            ],
            options={
                'verbose_name': '홈페이지 기본 정보',
                'verbose_name_plural': '홈페이지 기본 정보',
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('is_main',), name='one_main_branch'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(('is_main', False), ('is_public', True), _connector='OR'), name='main_must_be_public'),
        ),
        migrations.AddConstraint(
            model_name='sitecontent',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='single_site_content'),
        ),
    ]
