# Generated by Django 5.2.17 on 2026-10-04 18:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='이름')),
                ('edit_version', models.PositiveIntegerField(default=0)),
                ('job_title', models.CharField(blank=True, help_text='선택 입력입니다. 표시 순서나 권한에 영향을 주지 않습니다.', max_length=100, verbose_name='직급')),
                ('profile_alt', models.CharField(blank=True, max_length=200, verbose_name='프로필 사진 대체 설명')),
                ('short_intro', models.CharField(blank=True, max_length=300, verbose_name='한줄소개')),
                ('is_public', models.BooleanField(default=False, help_text='소속 지점도 공개일 때 표시됩니다. 비공개로 바꾸면 기존 소개도 고객 화면에서 사라집니다.', verbose_name='공개')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='지점 내 표시 순서')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainers', to='content.branch', verbose_name='소속 지점')),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainer_profiles', to='wagtailimages.image', verbose_name='프로필 사진')),
            ],
            options={
                'verbose_name': '트레이너',
                'verbose_name_plural': '트레이너',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainerCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('education', '학력'), ('award', '수상경력'), ('certification', '자격증'), ('experience', '주요 경력')], max_length=20, verbose_name='구분')),
                ('text', models.CharField(max_length=500, verbose_name='약력 내용')),
                ('trainer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='content.trainer')),
            ],
            options={
                'verbose_name': '약력',
                'verbose_name_plural': '약력',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='trainer',
            constraint=models.CheckConstraint(condition=models.Q(('is_public', False), models.Q(('profile_image__isnull', False), models.Q(('name', ''), _negated=True), models.Q(('short_intro', ''), _negated=True)), _connector='OR'), name='public_trainer_required_fields'),
        ),
        migrations.AddConstraint(
            model_name='trainercareer',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['education', 'award', 'certification', 'experience'])), name='trainer_career_fixed_category'),
        ),
        migrations.AddConstraint(
            model_name='trainercareer',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='trainer_career_nonempty_text'),
        ),
    ]
