# Generated by Django 5.2.17 on 2026-10-05 02:20

import django.db.models.deletion
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_trainer_and_career'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('live', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('category', models.CharField(choices=[('notice', '공지사항'), ('event', '이벤트')], default='notice', max_length=10, verbose_name='분류')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='본문')),
                ('cover_alt', models.CharField(blank=True, max_length=200, verbose_name='대표 이미지 대체 설명')),
                ('edit_version', models.PositiveIntegerField(default=0)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_covers', to='wagtailimages.image', verbose_name='대표 이미지')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
            ],
            options={
                'verbose_name': '공지·이벤트',
                'verbose_name_plural': '공지·이벤트',
                'permissions': [('publish_post', 'Can publish post')],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostImageUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_post_uses', to='wagtailimages.image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_image_uses', to='content.post')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.revision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['notice', 'event'])), name='post_fixed_category'),
        ),
        migrations.AddConstraint(
            model_name='postimageuse',
            constraint=models.UniqueConstraint(fields=('post', 'image'), name='post_image_use_unique'),
        ),
    ]
