# Generated by Django 5.2.17 on 2026-10-05 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_posts'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('message', models.TextField(blank=True, max_length=1000, verbose_name='안내 문구')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='이미지 대체 설명')),
                ('enabled', models.BooleanField(default=False, verbose_name='사용')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 일시')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 일시')),
                ('priority', models.PositiveIntegerField(default=0, help_text='작은 값이 먼저입니다.', verbose_name='우선순위')),
                ('edit_version', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='popups', to='wagtailimages.image', verbose_name='이미지')),
                ('post', models.OneToOneField(error_messages={'unique': '이 게시글의 팝업 설정이 이미 있습니다. 기존 설정을 편집하세요.'}, on_delete=django.db.models.deletion.PROTECT, related_name='popup', to='content.post', verbose_name='연결 게시글')),
            ],
            options={
                'verbose_name': '기간제 팝업',
                'verbose_name_plural': '기간제 팝업',
                'ordering': ['priority', '-starts_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('starts_at__lt', models.F('ends_at')), _connector='OR'), name='popup_valid_period'), models.CheckConstraint(condition=models.Q(('enabled', False), models.Q(('ends_at__isnull', False), ('starts_at__isnull', False), models.Q(('title', ''), _negated=True), models.Q(models.Q(('message', ''), _negated=True), ('image__isnull', False), _connector='OR')), _connector='OR'), name='popup_enabled_complete')],
            },
        ),
    ]
