# Generated by Django 5.2.17 on 2026-10-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address_confirmed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
