# Generated by Django 5.2.17 on 2026-10-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_branch_address_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='google_embed_url',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='google_map_address',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='google_map_confirmed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
